GET /enderecos HTTP/1.1
Host: localhost:8080
Content-Type: application/json

POST /enderecos HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "id": 1,
    "rua": "test St",
    "numero": "123",
    "cidade": "Test City",
    "estado": "Teste State",
    "cep": "12345678",
}

#---------------------------------------------

GET /pacotes HTTP/1.1
Host: localhost:8080
Content-Type: application/json


POST /pacotes HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "id": "12345",
    "destinatario": "Teste Dest",
    "endereco": {
        "id": 1
    },
    "status": "entregue"
}

#---------------------------------------------

GET /rastreamentos HTTP/1.1
Host: localhost:8080
Content-Type: application/json

